#  --- Build ---
FROM bitwalker/alpine-elixir-phoenix:1.10.3 AS builder

ENV CATENA_DB_USER=${CATENA_DB_USER}
ENV CATENA_DB_PASS=${CATENA_DB_PASS}
ENV CATENA_DB_NAME=${CATENA_DB_NAME}
ENV CATENA_DB_HOST=${CATENA_DB_HOST}
ENV CATENA_DB_POOL_SIZE=${CATENA_DB_POOL_SIZE}
ENV CATENA_SECRET_KEY_BASE=${CATENA_SECRET_KEY_BASE}
ENV CATENA_HOST_NAME=${CATENA_HOST_NAME}
ENV CATENA_HOST_PORT=${CATENA_HOST_PORT}
ENV CATENA_PASSWORD_RESET_TTL=${CATENA_PASSWORD_RESET_TTL}

WORKDIR /app
COPY . .
RUN MIX_ENV=prod mix do deps.get --only prod, deps.compile, phx.digest, release --overwrite

#  --- Run ---
FROM alpine:latest AS runner
RUN apk update && apk --no-cache --update add bash openssl

ENV CATENA_DB_USER=${CATENA_DB_USER}
ENV CATENA_DB_PASS=${CATENA_DB_PASS}
ENV CATENA_DB_NAME=${CATENA_DB_NAME}
ENV CATENA_DB_HOST=${CATENA_DB_HOST}
ENV CATENA_DB_POOL_SIZE=${CATENA_DB_POOL_SIZE}
ENV CATENA_SECRET_KEY_BASE=${CATENA_SECRET_KEY_BASE}
ENV CATENA_HOST_NAME=${CATENA_HOST_NAME}
ENV CATENA_HOST_PORT=${CATENA_HOST_PORT}
ENV CATENA_PASSWORD_RESET_TTL=${CATENA_PASSWORD_RESET_TTL}

WORKDIR /app
COPY --from=builder /app/_build/prod/rel/catena .

CMD ["bin/catena", "start"]